# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZYAPPFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZYAPPFramework
  
  pod 'ESTabBarController-swift'
  pod 'SHFullscreenPopGestureSwift'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire'
  pod 'WCDB.swift'
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'KeychainAccess'
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
  pod 'NVActivityIndicatorView'
  pod 'Toucan'#目前最高支持swift4.0
  
  target 'ZYAPPFrameworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZYAPPFrameworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
